name: End-to-end Regression tests
on: 
  schedule:
    - cron: '50 8 * * 1' 
jobs:
  End-to-End-run:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cypress run
        uses: cypress-io/github-action@v6
      
      - name: Cypress Test Report  
        uses: actions/upload-artifact@v4
        with:
          name: Mochawesome HTML Report
          path: cypress/reports/html # or path/to/artifact