name: End-to-end Regression tests
on: push
jobs:
  End-toEnd run:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cypress run
        uses: cypress-io/github-action@v6
      
      - name: Cypress Test Report  
        uses: actions/upload-artifact@v4
        with:
          name: Mochawesome HTML Report
          path: cypress/reports/html # or path/to/artifact